### ISSUE TITLE
Double click doesn't work in macOS

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/kv-electron#183]
**Describe the bug**
The application is correctly associated to the`.khj` files. However double clicking a `.khj` file only opens the application without loading the file.

Additionally, in a console, `open results.khj` also opens only the application without loading the file. The latter is useful to open the KV app from a jupyter notebook.

**Edit**: I thought this bug was repoducible, but sometimes it works fine!

**Platform / versions (please complete the following information):**
 - Platform: macOS 14
 - Version: 11.0.6

**Comment by stephanebouget** [comment]
ok, 

The file open event on Mac is delayed, and sometimes it takes too long to execute. Attempt to fix in 11.0.7
