### ISSUE TITLE
Add standard keyboard shortcuts in macOS

### ISSUE THREAD

**Issue by folmos-at-orange** [KhiopsML/kv-electron#184]
**Describe the feature**
Add these basic keyboard shortcuts of macOS:
- `⌘ + Q` : Quit
- `⌘ + O` : Open File

**Comment by stephanebouget** [comment]
### Covisu
![image](https://github.com/KhiopsML/kv-electron/assets/13203455/65d5462f-a3ca-4b6a-b9ae-41fe045160de)


### Visu
![image](https://github.com/KhiopsML/kv-electron/assets/13203455/83941f76-b9a5-45ab-acda-0ee2effc3ad6)

**Comment by folmos-at-orange** [comment]
In macOS  both KV (v11.0.7) and KC (v11.1.0) don't have shortcuts for opening, restart, exit, etc. 

<img width="864" alt="image" src="https://github.com/KhiopsML/kv-electron/assets/92923444/2ea6f63d-7352-48d7-a377-be8f57f5456c">

<img width="864" alt="image" src="https://github.com/KhiopsML/kv-electron/assets/92923444/9855f2c3-d439-42ee-afa4-90597b19955e">

<img width="877" alt="image" src="https://github.com/KhiopsML/kv-electron/assets/92923444/11092a62-51e1-4b66-9542-801a412e1be8">

<img width="877" alt="image" src="https://github.com/KhiopsML/kv-electron/assets/92923444/160ddfbc-49da-46d3-b661-98c5773e23ef">

**Comment by stephanebouget** [comment]
@folmos-at-orange yes it will be available in the next releases
Currently 11.0.7 is in DRAFT state for my tests purposes only.
You can delete it because this draft is broken.

I thought I was the only one to see the release drafts...
in the future, it is better never to install a draft version
